version: 2.1

executors:
  maven:
    docker:
      - image: cimg/openjdk:11.0.16
        user: root

workflows:
  test-and-build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          context:
            - cm-cloudsmith
            - cm-team-github
      - publish-cloudsmith:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          context:
            - cm-cloudsmith
            - cm-team-github

jobs:
  build:
    working_directory: ~/unified-content-model
    executor: maven
    steps:
      - checkout
        # Download and cache dependencies. comment updated
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "pom.xml" }}
      - run:
          name: Check maven pom files format (lint)
          command: |
            uname -a
            apt-get -qqy update
            apt-get install -qqy libxml2-utils
            xmllint pom.xml | XMLLINT_INDENT=$'\t' xmllint --format --encode utf-8 - > /tmp/a.xml; mv /tmp/a.xml pom.xml
            xmllint core/pom.xml | XMLLINT_INDENT=$'\t' xmllint --format --encode utf-8 - > /tmp/a.xml; mv /tmp/a.xml core/pom.xml
            xmllint model/pom.xml | XMLLINT_INDENT=$'\t' xmllint --format --encode utf-8 - > /tmp/a.xml; mv /tmp/a.xml model/pom.xml
            xmllint ws/pom.xml | XMLLINT_INDENT=$'\t' xmllint --format --encode utf-8 - > /tmp/a.xml; mv /tmp/a.xml ws/pom.xml
            # Ivalid pom.xml format if fail
            git diff --exit-code
      - run:
          name: Maven Verify
          command: |
            mkdir -p ~/.m2/
            curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" -v -o ~/.m2/settings.xml -L "https://raw.githubusercontent.com/Financial-Times/cloudsmith-settings/main/public-settings.xml"
            mvn clean verify jacoco:report coveralls:report -DrepoToken=${COVERALLS_TOKEN}
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dep-{{ checksum "pom.xml" }}

  publish-cloudsmith:
    working_directory: ~/unified-content-model
    executor: maven
    steps:
      - checkout:
          path: ~/unified-content-model
      - run:
          name: Publish Tag to CloudSmith repository
          command: |
            mkdir ~/.m2/
            curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" -v -o ~/.m2/settings.xml -L "https://raw.githubusercontent.com/Financial-Times/cloudsmith-settings/main/public-settings.xml"
            mvn versions:set -DnewVersion=${CIRCLE_TAG}
            mvn versions:commit
            mvn deploy
