version: 2.1

executors:
  maven:
    docker:
      - image: maven:3.6-jdk-11

workflows:
  test-and-build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          context:
            - cm-cloudsmith
            - cm-team-github
      - publish-cloudsmith:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          context:
            - cm-cloudsmith
            - cm-team-github

jobs:
  build:
    working_directory: ~/unified-content-model
    executor: maven
    steps:
      - checkout
      - run:
          name: Check maven pom files format (lint)
          command: |
            uname -a
            apt-get -qqy update
            apt-get install -qqy libxml2-utils
            xmllint pom.xml | XMLLINT_INDENT=$'\t' xmllint --format --encode utf-8 - > /tmp/a.xml; mv /tmp/a.xml pom.xml
            xmllint core/pom.xml | XMLLINT_INDENT=$'\t' xmllint --format --encode utf-8 - > /tmp/a.xml; mv /tmp/a.xml core/pom.xml
            xmllint model/pom.xml | XMLLINT_INDENT=$'\t' xmllint --format --encode utf-8 - > /tmp/a.xml; mv /tmp/a.xml model/pom.xml
            xmllint ws/pom.xml | XMLLINT_INDENT=$'\t' xmllint --format --encode utf-8 - > /tmp/a.xml; mv /tmp/a.xml ws/pom.xml
            # Ivalid pom.xml format if fail
            git diff --exit-code
      - run:
          name: Maven Verify
          command: |
            mkdir ~/.m2/
            curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" -v -o ~/.m2/settings.xml -L "https://raw.githubusercontent.com/Financial-Times/cloudsmith-settings/main/public-settings.xml"
            mvn clean verify jacoco:report coveralls:report -DrepoToken=${COVERALLS_TOKEN}
            rm -rf ~/.m2/*
  publish-cloudsmith:
    working_directory: ~/unified-content-model
    executor: maven
    steps:
      - checkout:
          path: ~/unified-content-model
      - run:
          name: Publish Tag to CloudSmith repository
          command: |
            mkdir ~/.m2/
            curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" -v -o ~/.m2/settings.xml -L "https://raw.githubusercontent.com/Financial-Times/cloudsmith-settings/main/public-settings.xml"
            mvn versions:set -DnewVersion=${CIRCLE_TAG}
            mvn versions:commit
            mvn deploy
            rm -rf ~/.m2/*
